### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by alexofrhodes** [G33kDude/CodeQuickTester#13]
I'm running it as Administrator.  

**Save As** works fine, but simple **Save** returns following error:
```

Error: Missing a required parameter.

Specifically: saveAs

	---- C:\Users\acer\Documents\GitHub\AutoHotkey\GeekDude\CodeQuickTester\lib\CQT.ahk
	090: }
	090: {
▶	090: Return  this.Save()
	090: }
	090: {

```

**Comment by G33kDude** [comment]
What version of the code are you running?

**Comment by alexofrhodes** [comment]
Hey, sorry for the inconvenience. 
I don't know what went wrong last time, today it is working. 
You got good stuff :D
