### ISSUE TITLE
Save File will only create a empty file and lose all the content.

### ISSUE THREAD

**Issue by nperovic** [G33kDude/CodeQuickTester#14]
https://github.com/G33kDude/CodeQuickTester/blob/e388c2c7f4b1780ec2e521877f28292f801463a8/lib/CQT.ahk#L529

Since Geek mentioned once in discord, I found it can easily be fixed by change `this.richCode.Value` to `this.richCode.Text`

```
FileOpen(this.FilePath, "w").Write(this.richCode.Text)
```

**Comment by G33kDude** [comment]
Fixed by https://github.com/G33kDude/CodeQuickTester/commit/54150e604277fd2914534b87eb90adf7455206f8
