### ISSUE TITLE
File -> New = Error at line 1.

### ISSUE THREAD

**Issue by hAirypAulsAck** [G33kDude/CodeQuickTester#5]
![image](https://user-images.githubusercontent.com/36932893/38643693-e33a9632-3d92-11e8-894f-7ec885455b44.png)

Couldn't find MZ and obviously nothing apparently wrong with line one.. I'm curious why the error line doesn't match up with the exception line?

**Comment by hAirypAulsAck** [comment]
In attempting to fix, I downloaded the source files from the release page of v2.6 to see if I was missing something (though I wasn't notified of any errors when compiling) and the RichCode.ahk folder is empty. When attempting to compile with ahk2exe (normally use scite) it notified my of the missing richcode.ahk lib.

**Comment by derz00** [comment]
Use the release .ahk file instead of the zip. 

[CodeQuickTester_v2.6.ahk](https://github.com/G33kDude/CodeQuickTester/releases/download/v2.6/CodeQuickTester_v2.6.ahk)

**Comment by hAirypAulsAck** [comment]
thank yer much
